server:
  port: 8002

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://192.168.170.10:3306/cs_user

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cs-member
  redis:
    host: 192.168.170.10
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100ms


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.gdufe.cs.entities


  #management是所有 actuator的配置
management:
  endpoints:
    web:
      exposure:
        include: '*' #以web方式暴露所有端点
    enabled-by-default: true  #默认开启所有监控端点
    #显示每个端点的详细信息
  endpoint:
    health:
      show-details: always