server:
  port: 9090

spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://192.168.170.10:3306/cs_works?serverTimezone=GMT%2b8
   username: root
   password: root

#mybatis:
#  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  application:
    name: cs-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

